import streamlit as st  # streamlit 관한 명령어 정의
import pandas as pd

st.title('ENGLISH NE high school 1 Hyun kwon Yang etc Word collection')
st.sidebar.subheader('Class of Robin')
option = st.sidebar.selectbox(
    'Please select a unit.',
    pd.Series(["unit1", "unit2", "unit3", "unit4", "unit5", "unit6", "unit7", "unit8", ]))
    # sidebar.selectbox에 관한 option
st.sidebar.subheader('')
st.sidebar.subheader('')
st.sidebar.subheader('')
st.sidebar.subheader('')
st.sidebar.subheader('')
st.sidebar.subheader('')
st.sidebar.subheader('')
st.sidebar.subheader('')
st.sidebar.subheader('')
st.sidebar.subheader('')
st.sidebar.markdown('')
st.sidebar.caption('bug report by E-mail')
st.sidebar.caption('rladmsgur0727@gmail.com')
'You choice : ', option     # option 선택 알림창

if option == "unit1":       # unit1일 때
    if st.button("View"):
        st.subheader('act on ~에 따라 행동하다')
        st.subheader('confident 자신감 있는')
        st.subheader('counsel ...에게 조언하다, 권고하다')
        st.subheader('cover up ~을 덮어 가리다, 감추다')
        st.subheader('face ~에 직면하다')
        st.subheader('feel like ~할 마음이 내키다')
        st.subheader('get along with ~와 잘 지내다, ...와 사이가 좋다')
        st.subheader('give ~ a shot ~을 한 번 시도해 보다')
        st.subheader('give ~ consideration ~을 검토하다, 숙고하다, 고려하다')
        st.subheader('involve ~을 참여시키다, 관여시키다')
        st.subheader('keep an eye out for 눈을 똑바로 뜨고 잘 살피다')
        st.subheader('make sure 분명히 ~하도록 하다')
        st.subheader('more than 매우, 정말')
        st.subheader('passion 열정, 격정')
        st.subheader('pay attention to ~에 주의를 기울이다')
        st.subheader('perspective 시각, 관점')
        st.subheader('photography (영화)촬영술')
        st.subheader('poem 시')
        st.subheader('poet 시인')
        st.subheader('psychologist 심리학자')
        st.subheader('pure 순수한')
        st.subheader('reflect on 곰곰이 생각하다, 숙고하다')
        st.subheader('remove ~을 제거하다')
        st.subheader('self-identity 자기 정체성')
        st.subheader('shoot for ~을 겨냥하다, ~을 목표로 하다')
        st.subheader('sign up for ...에 신청하다[등록하다, 가입하다]')
        st.subheader('since ~이므로, ~때문에')
        st.subheader('sooner or later 조만간, 머지않아')
        st.subheader('specialist 전문가')
        st.subheader('stick one’s toe in the water ~을 시험 삼아 해보다, 잘 하는지 알기 위해 시작하다')
        st.subheader('stick to 고수하다, 끈기 있게 하다')
        st.subheader('stretch ~을 쭉 펴다')
        st.subheader('suffer 더 나빠지다, 악화되다')
        st.subheader('take advantage of ~을 이용하다')
        st.subheader('to be honest 솔직히 말해서, 실은')
        st.subheader('try ~ing (시험 삼아) ...해보다')
        st.subheader('unfamiliar 낯선, 생소한')
        st.subheader('unique 유일한, 특유한')
        st.subheader('value ~를 중요하게 여기다, ~을 높이 평가하다, ~을 존중하다')
        st.subheader('wing 날개')
        st.subheader('yet 그런데도, 그렇지만')
if option == "unit2":       # unit2일 때
    if st.button("View"):
        st.subheader('about 약, 대략')
        st.subheader('aerobics 에어로빅')
        st.subheader('all night 밤새도록')
        st.subheader('as far as possible 가능한 한')
        st.subheader('avoid ~을 하지 않으려 하다, ~을 피하다')
        st.subheader('benefit 이익, 이점')
        st.subheader('berry 베리(딸기류의 작은 과실)')
        st.subheader('boost ~을 끌어올리다')
        st.subheader('brain power 지능, 지적 능력')
        st.subheader('circulation 혈액순환')
        st.subheader('curl up 몸을 웅크리다')
        st.subheader('curved 곡선의, 굽은, 휜')
        st.subheader('daily 매일, 날마다')
        st.subheader('dehydration 탈수(증)')
        st.subheader('disadvantage 불리한 점, 불리, 단점')
        st.subheader('effective 효과적인')
        st.subheader('elbow 팔꿈치')
        st.subheader('flavor ~에 맛을 내다')
        st.subheader('fruity 과일이 듬뿍 들어있는, 과일 맛이 나는')
        st.subheader('function 기능, 작용')
        st.subheader('glow 혈색, 홍조')
        st.subheader('hear from ~의 의견을 듣다')
        st.subheader('herbal 허브의, 약초의')
        st.subheader('herb 허브, 약초')
        st.subheader('hold a position 자세를 유지하다')
        st.subheader('host 사회자, 진행자')
        st.subheader('hydrate ~에 수분을 공급하다')
        st.subheader('ideal 이상적인, 완벽한')
        st.subheader('in fact 사실은')
        st.subheader('intake 섭취(량)')
        st.subheader('lead to ~으로 이어지다, ~을 가져오다')
        st.subheader('lean over ~위로 몸을 기울이다')
        st.subheader('lift up ~을 들어 올리다')
        st.subheader('maintain ~을 유지하다, 지속하다')
        st.subheader('neutral 중립인')
        st.subheader('none at all 아무 것도 없는')
        st.subheader('per ~당, ~마다')
        st.subheader('pillow 베개')
        st.subheader('posture 자세')
        st.subheader('post ~을 게시하다, 싣다')
        st.subheader('press-up 팔굽혀펴기')
        st.subheader('pressure 압력, 누르는 힘')
        st.subheader('prevent ~을 막다, 방지하다')
        st.subheader('push against ~을 밀다')
        st.subheader('real time 실제 시간')
        st.subheader('regularly 정기적으로, 규칙적으로')
        st.subheader('relatively 상대적으로, 비교적')
        st.subheader('repetition 반복')
        st.subheader('replace A with B A를 B로 교체하다[바꾸다]')
        st.subheader('reusable 재사용이 가능한, 재활용할 수 있는')
        st.subheader('snore 코를 골다')
        st.subheader('space 공간, 자리')
        st.subheader('specialist 전문가')
        st.subheader('stay in shape 건강을 유지하다')
        st.subheader('stiff 뻐근한, 뻣뻣한')
        st.subheader('straighten out ~을 곧게 펴다')
        st.subheader('straighten ~을 곧게 펴다')
        st.subheader('straight 곧은, 일직선의, 쭉 뻗은')
        st.subheader('strengthen ~을 강화하다, 단련하다')
        st.subheader('suffer from ~을 앓다')
        st.subheader('sugary 설탕이 들어 있는, 달콤한')
        st.subheader('support ~을 지탱하다')
        st.subheader('take in ~을 받아들이다, 마시다, 빨아들이다')
        st.subheader('turn to ~쪽으로 몸을 돌리다')
        st.subheader('up to ~까지')
        st.subheader('vote for ~에게 투표하다')
        st.subheader('weight 무게, 중량, 몸무게')
        st.subheader('wrinkle 주름(살)')
if option == "unit3":       # unit3일 때
    if st.button("View"):
        st.subheader("Alzheimer's disease 알츠하이머병")
        st.subheader('alert(명사) (경계) 경보')
        st.subheader('although 비록 ~일지라도')
        st.subheader('attach 부착하다')
        st.subheader('be struck 감명받다')
        st.subheader('be used to V ~하는데 사용되다')
        st.subheader('break into ~로 침입하다')
        st.subheader('bully 괴롭히는 사람들')
        st.subheader('bully 괴롭히는 사람들')
        st.subheader('by ~ing ~함으로써')
        st.subheader('campaign 캠페인')
        st.subheader('caregiver 돌보는 사람')
        st.subheader('circuit 회로')
        st.subheader('community 지역사회')
        st.subheader('conclude 결론짓다')
        st.subheader('contribute to ~ing ~에 공헌하다')
        st.subheader('deal with (병과) 싸우다')
        st.subheader('deeply 매우, 깊게')
        st.subheader('delight 기쁨')
        st.subheader('detect 감지하다')
        st.subheader('device 장치, 도구')
        st.subheader('disappoint 실망시키다')
        st.subheader('donate 기부하다')
        st.subheader('encourage 용기를 복돋다')
        st.subheader('entire 전체의')
        st.subheader('especially 특히')
        st.subheader('fail to V ~하지 못하다')
        st.subheader('gain 얻다')
        st.subheader('great soul 위대한 영혼(위대한 사람)')
        st.subheader('hateful 혐오스러운')
        st.subheader('hurtful 마음을 상하게 하는')
        st.subheader('in fact 사실')
        st.subheader('in the middle of ~의 도중에, 중간에')
        st.subheader('it takes (시간, 노력 등이) 걸리다, 필요로 하다')
        st.subheader('live up to (기대에) 부응하다, 맞춰살다')
        st.subheader('look forward to ~ing ~하는 것을 학수고대하다')
        st.subheader('mess 엉망인 상태')
        st.subheader('more than ~이상')
        st.subheader('move 감동시키다')
        st.subheader('no matter how 아무리 ~이더라도')
        st.subheader('nursing home 양로원')
        st.subheader('official 공식적인')
        st.subheader("of one's own 자기 자신의")
        st.subheader('once(접속사) 일단 ~ 하면')
        st.subheader('ordinary 일반적인')
        st.subheader('overcome 극복하다')
        st.subheader('patient 환자')
        st.subheader('plant(동사) 심다')
        st.subheader('post(동사) 게시하다')
        st.subheader('practically 사실상, 실제로')
        st.subheader('pressure 압력')
        st.subheader('probably 아마도')
        st.subheader('purpose 목적')
        st.subheader('put up 붙이다, 게시하다')
        st.subheader('recently 최근에')
        st.subheader('sacrifice 희생(하다)')
        st.subheader('scold 꾸짖다')
        st.subheader('set out 시작하다, 착수하다')
        st.subheader('several 몇몇의')
        st.subheader('share 공유하다')
        st.subheader('spread 퍼뜨리다')
        st.subheader('sticky note 접착 메모지')
        st.subheader('strength 힘')
        st.subheader('such as ~와 같은')
        st.subheader('such 그러한')
        st.subheader('suffer from ~으로 고통 받다')
        st.subheader('take action 조치를 취하다')
        st.subheader('take the place of ~를 대신하다')
        st.subheader("to one's 감정명사 ~하게도")
        st.subheader('toward ~쪽으로, ~를 향해서')
        st.subheader('trigger 일으키다, 유발시키다')
        st.subheader('wander 돌아다니다, 배회하다')
        st.subheader('whatever 무엇이든지')
        st.subheader('what ~ like (=how) 어떤지, 어떨지')
        st.subheader('wireless 무선의')
        st.subheader('work 작동하다')
if option == "unit4":       # unit4일 때
    if st.button("View"):
        st.subheader('a breath of fresh air 신선한 공기')
        st.subheader('all alone 완전히 혼자서, 정말 외로운')
        st.subheader('alternate between A and B A와 B 사이를 왔다 갔다 하다')
        st.subheader('attain ~을 달성하다, ~을 획득하다')
        st.subheader('a whole lot of 아주 많은 수[양]의 ~')
        st.subheader('beat ~을 이겨내다')
        st.subheader('be in need of ~을 필요로 하다, ~이 필요하다')
        st.subheader('benefit 이익, 이점')
        st.subheader('blow on ~에 숨을 내뿜다, ~을 후후불다')
        st.subheader('breathe out 숨을 내쉬다')
        st.subheader('breeze 산들바람')
        st.subheader('broad (미소 등이) 만면의, 얼굴에 가득한')
        st.subheader('broth 국물')
        st.subheader('chill ~을 차게 하다')
        st.subheader('commit to (doing) ~ ~(할 것)을 확실히 약속하다')
        st.subheader('cucumber 오이')
        st.subheader('cure all 만능해결책, 만병통치약')
        st.subheader('decide on ~ ~을 결정하다, 선택하다')
        st.subheader('degree 정도, 수준')
        st.subheader('easier said than done 말처럼 쉽지 않은')
        st.subheader('freshen up 상쾌하게 하다, 말끔히 하다')
        st.subheader('garlic 마늘')
        st.subheader('ginseng 인삼 (뿌리)')
        st.subheader('go for ~을 선택하다')
        st.subheader('happen to 우연히 ~하다')
        st.subheader('help out ~을 도와주다')
        st.subheader('herbal 약초의')
        st.subheader('hot spring 온천')
        st.subheader('investigate 살피다')
        st.subheader('look around ~을 둘러보다')
        st.subheader('luckily 운 좋게도, 다행히')
        st.subheader('match ~에 필적하다, 걸맞다')
        st.subheader('mustard 겨자 (소스)')
        st.subheader('needless to say 말할 필요도 없이, 당연하게')
        st.subheader('noodle 국수, 면')
        st.subheader('out of balance 균형을 잃고, 평정을 잃고')
        st.subheader('part 헤어지다, 작별하다')
        st.subheader('pepper 고추')
        st.subheader('philosophy 철학')
        st.subheader('progress 경과하다, 진행되다')
        st.subheader('refreshing 상쾌하게 하는, 기운 나게하는')
        st.subheader('relaxing 편안하게 하는, 긴장을 풀어주는')
        st.subheader('right away 즉시, 곧 바로')
        st.subheader('rop into ~에 들르다')
        st.subheader('saying 속담, 격언')
        st.subheader('show A to B A를 B로 안내하다')
        st.subheader('sleepless 잠 못 이루는, 밤잠을 설치는')
        st.subheader('spice 향신료, 양념')
        st.subheader('stay around (떠나지 않고) 근처[곁]에 남아있다')
        st.subheader('steam 김, 수증기')
        st.subheader('stuff ~의 속을 채우다')
        st.subheader('tender 부드러운, 연한')
        st.subheader('tune up 조정, 조율')
if option == "unit5":       # unit5일 때
    if st.button("View"):
        st.subheader('affordable (가격이) 알맞은')
        st.subheader('aim 목표로 하다')
        st.subheader('alter (옷을) 고치다')
        st.subheader('appeal 매력')
        st.subheader('attempt 시도하다')
        st.subheader('at the same time 동시에')
        st.subheader('bag (봉지, 가방 등에) 넣다')
        st.subheader('bamboo 대나무')
        st.subheader('bargain (정상 가격보다) 싸게 사는 물건')
        st.subheader('best of all 무엇보다도, 우선')
        st.subheader('be surrounded by ~에 둘러싸이다')
        st.subheader('browse (가게 안의 물건들을) 둘러보다')
        st.subheader('can afford to (경제적으로)~할 여유가 있다')
        st.subheader('carbon 탄소')
        st.subheader('care for ~을 보살피다, 돌보다')
        st.subheader('charity 자선 단체')
        st.subheader('come up with (아이디어)를 떠올리다')
        st.subheader('concern 걱정')
        st.subheader('consideration 고려')
        st.subheader('cost 비용이 들게 하다, 비용이 들다')
        st.subheader('dig out (오래 감춰지거나 잊혀 진 것을) 들춰내다[찾아내다]')
        st.subheader('donate (특히 자선단체에) 기부[기증] 하다')
        st.subheader('do one’s part 역할을 하다')
        st.subheader('ethically 윤리적으로')
        st.subheader('experiment 실험하다')
        st.subheader('fabric 옷감, 직물')
        st.subheader('fiber 섬유')
        st.subheader('fixed-up 수리된, 고쳐진')
        st.subheader('focus on ~에 초점을 맞추다, ~에 주력하다')
        st.subheader('footprint 발자국')
        st.subheader('garment 의류')
        st.subheader('get into 들어서다')
        st.subheader('have access to ~에 접근하다')
        st.subheader('important 중요한')
        st.subheader('in itself 그 자체로')
        st.subheader('instead of ~대신에')
        st.subheader('in the meantime 그 동안[사이]에, 한편')
        st.subheader('item 물건, 품목')
        st.subheader('join forces with ~와 협력하다, 힘을 합치다')
        st.subheader('keep ~ in mind ~을 명심하다, ~을 마음에 담아 두다')
        st.subheader('latest 최근의, 최신의')
        st.subheader('launch 시작하다, 착수하다')
        st.subheader('make a decision 결심하다')
        st.subheader('make sure to 반드시 ~하다')
        st.subheader('mend 수리하다, 고치다')
        st.subheader('millions of 수백만의')
        st.subheader('motivate 이유가 되다, 동기를 부여 하다')
        st.subheader('natural 자연의, 천연의')
        st.subheader('once 일단 ~하면')
        st.subheader('organically 유기적으로')
        st.subheader('pastime 취미')
        st.subheader('pioneer 개척자, 선구자')
        st.subheader('possibly 아마')
        st.subheader('preserve 지키다, 보존하다')
        st.subheader('promote 홍보하다')
        st.subheader('publicize (일반 사람들에게) 알리다, 홍보하다')
        st.subheader('renewable (천연자원 등이) 재생 가능한')
        st.subheader('resist 저항하다, 거부하다')
        st.subheader('respect 존중하다, 존경하다')
        st.subheader('retail 소매(업)의')
        st.subheader('reward 보상하다')
        st.subheader('saying 격언')
        st.subheader('second-hand 중고의')
        st.subheader('sew 바느질 하다')
        st.subheader('source (특정한 곳에서) 얻다')
        st.subheader('store 가게, 상점, 점포, 저장하다')
        st.subheader('sustainable 지속 가능한')
        st.subheader('take responsibility for ~에 책임을 지다')
        st.subheader('thrill 흥분, 설렘')
        st.subheader('treasure 보물')
        st.subheader('unique 독특한, 유일한')
        st.subheader('wardrobe 옷장')
        st.subheader('waste 쓰레기, 낭비하다')
if option == "unit6":       # unit6일 때
    if st.button("View"):
        st.subheader('account (구체적이고 상세한) 설명,기술')
        st.subheader('appear 나타나다, 등장하다')
        st.subheader('as long as ~하는 한')
        st.subheader('as much as ~만큼이나, ~ 정도까지 많이')
        st.subheader('backward 뒤쪽으로, 뒤로')
        st.subheader('baobab 바오바브나무')
        st.subheader('bark 나무껍질')
        st.subheader('behave 행동하다, 처신하다')
        st.subheader('be talented at ~에 재능이 있다')
        st.subheader('blossom 꽃, 꽃이 피다')
        st.subheader('branch 나뭇가지')
        st.subheader('complaint 불평, 항의')
        st.subheader('create 창조하다')
        st.subheader('decorate 장식하다')
        st.subheader('demonstrate 실례로 보여주다, 논증하다')
        st.subheader('develop 발달하다, 성장하다')
        st.subheader('diameter 지름, 직경')
        st.subheader('due to ~ 때문에')
        st.subheader('enable ~할 수 있게 하다')
        st.subheader('encounter 맞닥뜨리다, (우연히) 만나다')
        st.subheader('enormous 거대한, 막대한')
        st.subheader('except for ~을 제외하고는')
        st.subheader('factually 실제로, 사실상')
        st.subheader('feather 깃털')
        st.subheader('feed 먹이를 먹다')
        st.subheader('fig tree 무화과나무')
        st.subheader('flame tree 호주오동나무')
        st.subheader('flap (새가 날개를) 퍼덕거리다')
        st.subheader('forward 앞쪽으로, 앞으로')
        st.subheader('gain 얻다, 입수하다')
        st.subheader('hover 공중을 맴돌다, (새가) 공중에서 정지하다')
        st.subheader('huge 거대한, 엄청난')
        st.subheader('hummingbird 벌새')
        st.subheader('insight 통찰력, 직관')
        st.subheader('jealous 질투하는, 시기하는')
        st.subheader('leftover 나머지의, 남은, 나머지, 남은 것')
        st.subheader('liquid 액체')
        st.subheader('loss 손실, 분실, 상실')
        st.subheader('magnificent 참으로 아름다운, 훌륭한')
        st.subheader('mate (한 쌍을 이루는 새, 동물의) 짝')
        st.subheader('Mayan 마야 사람, 마야 사람의, 마야 사람말의')
        st.subheader('midair 공중, 상공')
        st.subheader('myth 신화, 근거 없는 믿음')
        st.subheader('offer 제공하다, 주다')
        st.subheader('palm tree 야자나무')
        st.subheader('plain 수수한, 장식이 없는')
        st.subheader('poorly 형편없이, 불완전하게')
        st.subheader('promise 약속하다')
        st.subheader('pull up 빼다, 뽑다, 끌어올리다')
        st.subheader('rainy season 우기, 장마철')
        st.subheader('recognize 알아보다, 인식하다')
        st.subheader('replant 다시 심다, 이식하다')
        st.subheader('rest 나머지, 휴식, 휴식을 취하다')
        st.subheader('root-like 뿌리 같은')
        st.subheader('seasoning 양념')
        st.subheader('sideways 옆으로 비스듬히')
        st.subheader('source 원천, 근원')
        st.subheader('store 저장하다, 보관하다')
        st.subheader('stroke (새의) 한 번 날개치기')
        st.subheader('survive 생존하다, 살아남다')
        st.subheader('tiny 아주 작은')
        st.subheader('trunk (나무의) 몸통')
        st.subheader('upside-down 거꾸로 된, 뒤집힌')
        st.subheader('up to ~까지')
        st.subheader('valuable 소중한, 귀중한')
        st.subheader('view 관점, 견해, 시야, 경관')
        st.subheader('waste 낭비하다, 허비하다')
        st.subheader('weakness 약점, 결점')
if option == "unit7":       # unit7일 때
    if st.button("View"):
        st.subheader('actual 실제의')
        st.subheader('agree 동의하다')
        st.subheader('anniversary 기념일')
        st.subheader('area 지역')
        st.subheader('argue 입증하다')
        st.subheader('as well 또한, 마찬가지로')
        st.subheader('at last 마침내')
        st.subheader('be about to~ 막 ~하려고 하다')
        st.subheader('be considered ~로 여겨지다, ~로 간주되다')
        st.subheader('be covered with ~로 덮여있다')
        st.subheader('bed-and-breakfast 아침식사를 제공하는 숙박, 민박')
        st.subheader('be filled with ~로 가득 차다')
        st.subheader('be ready for ~할 준비가 되다')
        st.subheader('by the time ~할 때까지, ~할 즈음')
        st.subheader('canal 운하')
        st.subheader('cathedral 대성당')
        st.subheader('celebrate 기념하다, 축하하다')
        st.subheader('center 중심')
        st.subheader('character (책, 영화의) 등장인물, 성격, 특징')
        st.subheader('charming 매력적인')
        st.subheader('climb 오르다, 올라가다')
        st.subheader('closely 가까이, 밀접하게, 친밀하게')
        st.subheader('colorful 화려한, 다채로운')
        st.subheader('contract 계약')
        st.subheader('craft (수)공예, 기술')
        st.subheader('cultural 문화의')
        st.subheader('dazzling 눈부신, 휘황찬란한')
        st.subheader('defend 옹호하다, 방어하다')
        st.subheader('destination 목적지')
        st.subheader('disappoint 실망시키다')
        st.subheader('discuss 논의하다, 상의하다')
        st.subheader('dozens of 수십의')
        st.subheader('elegant 우아한')
        st.subheader('escape from ~에서 탈출하다')
        st.subheader('extremely 극도로, 극히')
        st.subheader('factory 공장')
        st.subheader('female 여성인, 여성의')
        st.subheader('flesh (사람, 동물의) 살, 고기')
        st.subheader('flight 비행')
        st.subheader('float down 떠내려가다')
        st.subheader('fly (비행기·우주선을) 타다[타고 가다]')
        st.subheader('glass-blower 유리 부는 직공, 유리 공예가')
        st.subheader('gondola 곤돌라(베니스에서 운하를 오가는 기다란 배)')
        st.subheader('hide 숨기다')
        st.subheader('hold 가지다, 담다')
        st.subheader('huge 거대한, 엄청난')
        st.subheader('identity 신분, 정체')
        st.subheader('imagine 상상하다, (마음속으로) 그리다')
        st.subheader('impressive 인상적인, 감동적인')
        st.subheader('impress 깊은 인상을 주다, 감명을 주다')
        st.subheader('lead to ~로 연결되다, 이어지다')
        st.subheader('lump 덩어리')
        st.subheader('melt (열 때문에 액체가 되도록)녹다[녹이다]')
        st.subheader('memory 기억')
        st.subheader('merchant 상인, 무역상')
        st.subheader('mosaic 모자이크')
        st.subheader('movement 움직임, 동작')
        st.subheader('muddy 진흙투성이의')
        st.subheader('mythological 신화의')
        st.subheader('myth 신화')
        st.subheader('naturally 물론, 당연히, 자연스럽게')
        st.subheader('nearly 거의')
        st.subheader('one of a kind 유일한 것, 독특한 것')
        st.subheader("on one’s way back to ~로 돌아오는 길에")
        st.subheader('palace 궁전')
        st.subheader('path 길')
        st.subheader('perform 공연하다')
        st.subheader('pick out ~을 고르다')
        st.subheader('pound (가슴이) 마구 뛰다, 쿵쾅거리다')
        st.subheader('powerful 강한, 강렬한')
        st.subheader('practice 연습하다')
        st.subheader('preparation 준비')
        st.subheader('pretend ~인 척하다')
        st.subheader('professional 전문적인')
        st.subheader('realize 1. 실현되다 2. 깨닫다, 알게 되다')
        st.subheader('real 진짜의, 실제의')
        st.subheader('refreshing 신선한, 원기를 북돋우는')
        st.subheader('ride 타다')
        st.subheader('right away 당장, 바로')
        st.subheader('rightful 합법적인, 정당한')
        st.subheader('run 1. 달리다 2. 운영하다, 경영하다')
        st.subheader('save the day 궁지를 벗어나다, 가까스로해결하다')
        st.subheader('significant 중요한')
        st.subheader('skillful 숙련된, 솜씨 좋은')
        st.subheader('souvenir 기념품')
        st.subheader('square 1. 광장 2. 정사각형')
        st.subheader('steer 조정하다')
        st.subheader('step 발을 내디디다')
        st.subheader('suffering 고통, 괴로움')
        st.subheader('suggest (아이디어·계획을) 제안[제의]하다')
        st.subheader('take a trip 여행가다')
        st.subheader('take a turn 교대를 바꾸다, 순서를 바꾸다')
        st.subheader('tear 1. 눈물 2. 찢다')
        st.subheader('thrilled 아주 흥분한, 신난')
        st.subheader('tool 도구, 기구')
        st.subheader('trial 재판, 공판')
        st.subheader('turn A into B A를 B로 바뀌다, ~이 되다, ~로 변하다')
        st.subheader('turn 순서')
        st.subheader('unless ~하지 않는다면')
        st.subheader('used to 동사원형 ~하곤 했다.')
        st.subheader('wet 젖은')
        st.subheader('work of art 미술품, 예술품')
if option == "unit8":
    if st.button("View"):
        st.subheader('absorb 흡수하다')
        st.subheader('aluminum 알루미늄')
        st.subheader('a variety of 다양한')
        st.subheader('avoid 피하다')
        st.subheader('backward 뒤로')
        st.subheader('bend 구부러지다')
        st.subheader('blow 치기, 타격')
        st.subheader('bulky 부피가 큰, 거대한')
        st.subheader('cause 야기하다')
        st.subheader('comfortable 편안한')
        st.subheader('conclude 결론을 내리다')
        st.subheader('conclusion 결론, 판단')
        st.subheader('construction site 건설 현장')
        st.subheader('container 용기')
        st.subheader('cover A with B A를 B로 덮다')
        st.subheader('crash (자동차 충돌·항공기 추락)사고')
        st.subheader('credit A as B A를 B로 여기다')
        st.subheader('damage 손상, 피해')
        st.subheader('date back to (기원이) ~로 거슬러 올라가다')
        st.subheader('decade 십 년')
        st.subheader('despite ~에도 불구하고')
        st.subheader('detailed 상세한')
        st.subheader('device (특정 작업을 위해 고안된)장치[기구]')
        st.subheader('downward 아래쪽으로')
        st.subheader('endure 참다, 견디다')
        st.subheader('far from 전혀 ~이 아닌, ~와는 거리가 먼')
        st.subheader('flexibility 유연성')
        st.subheader('frequency 빈도, 빈도수')
        st.subheader('frequently 자주, 흔히')
        st.subheader('frontal 정면의, 머리 앞부분의')
        st.subheader('function (사람·사물의) 기능')
        st.subheader('goal 목표')
        st.subheader('hammer 1. n. 망치 2. v. 쿵쿵 치다,두들기다')
        st.subheader('imitate 모방하다')
        st.subheader('impact 1. 영향 2. 충격, 충돌')
        st.subheader('improvement 향상, 개선')
        st.subheader('injury 부상, 상해')
        st.subheader('innovation 혁신, 쇄신')
        st.subheader('insurance 보험')
        st.subheader('involve 수반하다, 관련시키다')
        st.subheader('layer (하나의 표면이나 여러 표면 사이를 덮고 있는) 막')
        st.subheader('likely to 동사원형 ~할 가능성이 있는')
        st.subheader('look into ~을 조사하다, ~을 들여다 보다')
        st.subheader('manage to 동사원형 겨우 ~하다')
        st.subheader('manufacturer 제조업자')
        st.subheader('massive 거대한, 부피가 큰')
        st.subheader('mechanical 기계적인, 기술적인')
        st.subheader('mental 정신의, 마음의')
        st.subheader('notice 의식하다, 알다')
        st.subheader('numerous 수많은')
        st.subheader('on average 평균적으로')
        st.subheader('origin 기원, 근원')
        st.subheader('pack A with B A를 B로 채우다')
        st.subheader('peck (부리로) 쪼다, 쪼아 먹다')
        st.subheader('physical 1.육체의, 신체의 2. 물리적인')
        st.subheader('pioneer 선구자, 개척자')
        st.subheader('positive 긍정적인')
        st.subheader('powerful 강력한, 매우 효과적인')
        st.subheader('protective 보호하는')
        st.subheader('protect 보호하다')
        st.subheader('realization 1. 깨달음 2. 실현')
        st.subheader('repeated 반복되는')
        st.subheader('reproduce 재생하다, 재현하다')
        st.subheader('rubber 고무')
        st.subheader('search for ~을 찾다')
        st.subheader('serious 심각한')
        st.subheader('shock 충격')
        st.subheader('skull 두개골')
        st.subheader('soften 부드럽게 하다')
        st.subheader('somehow 어떻게든')
        st.subheader('steel 강철')
        st.subheader('the very 바로, ~야 말로')
        st.subheader('tightly 단단히, 꽉')
        st.subheader('tip 끝부분')
        st.subheader('various 다양한')
        st.subheader('wearer 착용하는 사람, 착용자')
        st.subheader('yet ~ 인데도, 그럼에도 불구하고')
